const PROPERTIES = [
  {
    id: "p1",
    title: "Casa 4H con jardín privado",
    type: "venta",
    city: "caracas",
    location: "La Lagunita, Caracas",
    neighborhood: "La Lagunita",
    price: "$240,000",
    bedrooms: 4, bathrooms: 3, area: 320, parking: 2,
    badge: "Título verificado", verified: true, hasTour: false,
    mainImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=900&auto=format&fit=crop",
    ],
    description: "Espectacular residencia de 4 habitaciones en la exclusiva urbanización La Lagunita. Amplio jardín privado de 200 m², piscina climatizada, cuarto de servicio independiente y garaje doble cubierto. Completamente remodelada en 2022 con acabados de primera línea: pisos de mármol italiano, cocina equipada con island central y closets de diseño en cada habitación.",
    amenities: ["Piscina climatizada","Jardín privado 200 m²","Cuarto de servicio","Garaje doble cubierto","Seguridad 24/7","Cisterna y planta eléctrica","Jacuzzi","Sala de estudio","BBQ cubierto","Cuarto de juegos"],
    highlights: ["Zona verde exclusiva y vigilada","Remodelación completa 2022","Escritura limpia sin gravámenes","Acepta crédito bancario"],
    agent: { initials:"MF", name:"María Fernanda García", role:"Agente certificada · 8 años exp.", phone:"58412555010", responseTime:"Responde en < 1 hora" },
    legal: { titleVerified:true, noEncumbrances:true, noInformalOccupancy:true, agentVerified:true, freshMedia:true, verifiedDate:"12 Jun 2026", docNumber:"IV-2026-0312" }
  },
  {
    id: "p2",
    title: "Apartamento renovado 2H",
    type: "venta",
    city: "caracas",
    location: "Altamira, Caracas",
    neighborhood: "Altamira",
    price: "$98,500",
    bedrooms: 2, bathrooms: 2, area: 110, parking: 1,
    badge: "Tour 360°", verified: true, hasTour: true,
    mainImage: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=900&auto=format&fit=crop",
    ],
    description: "Elegante apartamento de 2 habitaciones en el corazón de Altamira. Totalmente renovado en 2023: porcelana 60×60, cocina integral con electrodomésticos Bosch, baños con accesorios de diseño. Vista despejada a El Ávila desde el balcón. El edificio cuenta con gimnasio, piscina comunal y salón de fiestas.",
    amenities: ["Balcón vista El Ávila","Gimnasio del edificio","Salón de fiestas","Piscina comunal","Vigilancia 24/7","Ascensores","Electrodomésticos incluidos","Cisterna y bomba"],
    highlights: ["Renovación completa 2023","Vista a El Ávila despejada","Sector premium con alta demanda","Escritura limpia"],
    agent: { initials:"CR", name:"Carlos Rodríguez", role:"Agente senior · 12 años exp.", phone:"58414555020", responseTime:"Responde en < 2 horas" },
    legal: { titleVerified:true, noEncumbrances:true, noInformalOccupancy:true, agentVerified:true, freshMedia:true, verifiedDate:"8 Jun 2026", docNumber:"IV-2026-0287" }
  },
  {
    id: "p3",
    title: "Penthouse vista a la ciudad",
    type: "venta",
    city: "caracas",
    location: "Country Club, Caracas",
    neighborhood: "Country Club",
    price: "$410,000",
    bedrooms: 3, bathrooms: 4, area: 280, parking: 3,
    badge: "Título verificado", verified: true, hasTour: true,
    mainImage: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210491892-03d54079571b?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560185127-6a5a71e7a223?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&auto=format&fit=crop",
    ],
    description: "Extraordinario penthouse de 3 habitaciones y 4 baños en torre premium del Country Club. Terraza privada de 120 m² con piscina propia y jacuzzi, vista panorámica 360° sobre Caracas. Dos plantas con doble altura en sala principal. Acabados de lujo: mármol, cocina italiana Scavolini, sistema domótico Crestron.",
    amenities: ["Terraza 120 m² privada","Piscina en terraza","Vista 360° Caracas","Doble altura sala","Sistema domótico","Cocina Scavolini","3 estacionamientos","Seguridad ejecutiva","Cuarto de servicio","Bodega privada"],
    highlights: ["Última unidad disponible","Vista más privilegiada del sector","Acabados únicos de lujo","Documentación completa"],
    agent: { initials:"MF", name:"María Fernanda García", role:"Agente certificada · 8 años exp.", phone:"58412555010", responseTime:"Responde en < 1 hora" },
    legal: { titleVerified:true, noEncumbrances:true, noInformalOccupancy:true, agentVerified:true, freshMedia:true, verifiedDate:"10 Jun 2026", docNumber:"IV-2026-0301" }
  },
  {
    id: "p4",
    title: "Apartamento 3H · Torre Mara",
    type: "venta",
    city: "caracas",
    location: "Las Mercedes, Caracas",
    neighborhood: "Las Mercedes",
    price: "$185,000",
    bedrooms: 3, bathrooms: 2, area: 145, parking: 1,
    badge: "Tour 360°", verified: true, hasTour: true,
    mainImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616137466211-f939a420be84?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1556909094-a3c20a93a8ec?w=900&auto=format&fit=crop",
    ],
    description: "Luminoso apartamento de 3 habitaciones en la emblemática Torre Mara de Las Mercedes. Sala-comedor integrado con balcón corrido, cocina abierta con barra desayunadora y cuarto de servicio. Las Mercedes ofrece la mejor oferta gastronómica y financiera de Caracas a pasos del edificio.",
    amenities: ["Balcón corrido","Cocina abierta con barra","Cuarto de servicio","Piscina del edificio","Gimnasio","Sala de reuniones","Ascensores alta velocidad","Generador completo"],
    highlights: ["Centro financiero de Caracas","Edificio con infraestructura completa","Alta rentabilidad de alquiler","Escritura limpia"],
    agent: { initials:"AP", name:"Ana Patricia Mendoza", role:"Agente certificada · 6 años exp.", phone:"58424555030", responseTime:"Responde en < 3 horas" },
    legal: { titleVerified:true, noEncumbrances:true, noInformalOccupancy:true, agentVerified:true, freshMedia:true, verifiedDate:"14 Jun 2026", docNumber:"IV-2026-0329" }
  },
  {
    id: "p5",
    title: "Townhouse 3H El Hatillo",
    type: "venta",
    city: "caracas",
    location: "El Hatillo, Caracas",
    neighborhood: "El Hatillo",
    price: "$162,000",
    bedrooms: 3, bathrooms: 3, area: 180, parking: 2,
    badge: "Título verificado", verified: true, hasTour: false,
    mainImage: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=900&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1585128792020-803d29415281?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=900&auto=format&fit=crop",
    ],
    description: "Encantador townhouse de 3 habitaciones en conjunto residencial cerrado del Hatillo. Zona boscosa y climatizada naturalmente, ideal para familias. Jardín propio con BBQ, sala de estar doble con chimenea y cocina renovada. Conjunto con vigilancia 24 horas, áreas verdes y cancha de tenis.",
    amenities: ["Jardín propio con BBQ","Chimenea en sala","Conjunto residencial cerrado","Áreas verdes comunes","Vigilancia 24/7","Cancha de tenis comunal","Garaje doble","Cuarto de servicio"],
    highlights: ["Zona fresca y arbolada","Clima natural ideal todo el año","Comunidad familiar establecida","Documentación en regla"],
    agent: { initials:"CR", name:"Carlos Rodríguez", role:"Agente senior · 12 años exp.", phone:"58414555020", responseTime:"Responde en < 2 horas" },
    legal: { titleVerified:true, noEncumbrances:true, noInformalOccupancy:true, agentVerified:true, freshMedia:true, verifiedDate:"5 Jun 2026", docNumber:"IV-2026-0271" }
  },
  {
    id: "p6",
    title: "Apartamento 2H Bello Campo",
    type: "alquiler",
    city: "caracas",
    location: "Bello Campo, Caracas",
    neighborhood: "Bello Campo",
    price: "$1,800/mes",
    bedrooms: 2, bathrooms: 2, area: 95, parking: 1,
    badge: "Tour 360°", verified: true, hasTour: true,
    mainImage: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1545579133-99bb5ad189be?w=900&auto=format&fit=crop",
    ],
    description: "Moderno apartamento amoblado de 2 habitaciones en Bello Campo, disponible de inmediato. Equipado con electrodomésticos de alta gama, muebles de diseño y todos los servicios incluidos. Piso 8 con vista despejada. Ideal para ejecutivos, profesionales o venezolanos retornando desde el exterior.",
    amenities: ["Totalmente amoblado","Electrodomésticos incluidos","Internet fibra óptica","Agua caliente solar","Aire acondicionado","Conserje 24/7","Balcón vista ciudad","Lavandería en unidad"],
    highlights: ["Disponible de inmediato","Totalmente equipado","Contrato flexible desde 6 meses","Depósito equivalente a 2 meses"],
    agent: { initials:"AP", name:"Ana Patricia Mendoza", role:"Agente certificada · 6 años exp.", phone:"58424555030", responseTime:"Responde en < 3 horas" },
    legal: { titleVerified:true, noEncumbrances:true, noInformalOccupancy:true, agentVerified:true, freshMedia:true, verifiedDate:"15 Jun 2026", docNumber:"IV-2026-0341" }
  }
];
